// DTown East Alum - static data snapshot
// Pulled from real league records as of July 2026. Refresh manually until
// the nflverse/Sleeper/Yahoo sync pipeline described in the architecture
// doc is built.

const OWNERS = [
  { slug: "brett-mariani", name: "Brett Mariani", seasons: 18, record: "141-103-1", winPct: 57.8, pf: 28789.2, pa: 27832.4, playoffs: 9, finals: 2, titles: 1, runnerUp: 2, third: 2, highScore: 211.33, team2025: "Eskimo Brothers" },
  { slug: "greg-yayac", name: "Greg Yayac", seasons: 18, record: "138-105-2", winPct: 56.7, pf: 28930.6, pa: 27836.0, playoffs: 10, finals: 5, titles: 2, runnerUp: 3, third: 1, highScore: 206.75, team2025: "Thug Lifo" },
  { slug: "colin-maxwell", name: "Colin Maxwell", seasons: 18, record: "133-110-2", winPct: 54.7, pf: 27970.0, pa: 27488.0, playoffs: 7, finals: 3, titles: 1, runnerUp: 2, third: 1, highScore: 214.44, team2025: "CeeDeez Nuts" },
  { slug: "austen-musso", name: "Austen Musso", seasons: 18, record: "121-122-2", winPct: 49.8, pf: 28256.3, pa: 28124.5, playoffs: 10, finals: 3, titles: 1, runnerUp: 2, third: 4, highScore: 203.15, team2025: "Nowhere to go but up" },
  { slug: "chris-mcfarland", name: "Chris McFarland", seasons: 15, record: "100-102-1", winPct: 49.5, pf: 22920.3, pa: 23292.1, playoffs: 6, finals: 5, titles: 3, runnerUp: 2, third: 1, highScore: 189.70, team2025: "Return of the Mac" },
  { slug: "jon-bradley", name: "Jon Bradley", seasons: 17, record: "112-115-4", winPct: 49.4, pf: 26271.9, pa: 26675.2, playoffs: 9, finals: 2, titles: 1, runnerUp: 1, third: 4, highScore: 196.70, team2025: "Broboken No Jokin" },
  { slug: "bobby-mainello", name: "Bob Mainello", seasons: 18, record: "119-124-2", winPct: 49.0, pf: 27825.2, pa: 27737.9, playoffs: 9, finals: 2, titles: 2, runnerUp: 0, third: 2, highScore: 190.30, team2025: "GoLong Hellen Keller" },
  { slug: "mike-bertha", name: "Mike Bertha", seasons: 18, record: "119-124-2", winPct: 49.0, pf: 27494.3, pa: 27559.8, playoffs: 7, finals: 4, titles: 2, runnerUp: 3, third: 1, highScore: 202.70, team2025: "JBLA" },
  { slug: "tony-yacenda", name: "Tony Yacenda", seasons: 18, record: "118-126-1", winPct: 48.4, pf: 27328.1, pa: 27882.7, playoffs: 7, finals: 2, titles: 2, runnerUp: 1, third: 1, highScore: 207.00, team2025: "Playoff Dark Horse" },
  { slug: "james-snyder", name: "James Snyder", seasons: 15, record: "96-106-1", winPct: 47.5, pf: 23880.1, pa: 23837.4, playoffs: 3, finals: 1, titles: 1, runnerUp: 0, third: 1, highScore: 191.20, team2025: "Drafted & Managed With AI" },
  { slug: "justin-claffey", name: "Justin Claffey", seasons: 18, record: "114-129-2", winPct: 46.9, pf: 27237.9, pa: 27738.5, playoffs: 7, finals: 5, titles: 4, runnerUp: 1, third: 0, highScore: 192.51, team2025: "Black Swans" },
  { slug: "dave-orr", name: "David Orr", seasons: 18, record: "106-137-2", winPct: 43.7, pf: 27402.0, pa: 28341.0, playoffs: 2, finals: 2, titles: 2, runnerUp: 1, third: 0, highScore: 207.15, team2025: "A Team Has No Name" },
];

const BUDGETS_2026 = {
  "jon-bradley": 200, "james-snyder": 230, "austen-musso": 183, "dave-orr": 226,
  "tony-yacenda": 174, "brett-mariani": 188, "justin-claffey": 206, "chris-mcfarland": 223,
  "greg-yayac": 200, "bobby-mainello": 200, "colin-maxwell": 200, "mike-bertha": 170,
};

const DEFENDING_CHAMPION = "mike-bertha";

// Structured, not prose: each entry is just "player -> team that received them",
// exactly matching the source trade log's own unambiguous notation. The
// human-readable sentence is generated by tradeSummary() in app.js so there
// is no hand-typed "sent/received/for" copy that can get the direction
// backwards - see the note on that function for why this replaced a plain
// summary string.
const RECENT_TRADES = [
  {
    date: "2025-11-23",
    moves: [
      { player: "Jauan Jennings", to: "JBLA" },
      { player: "Jordan Mason", to: "Return of the Mac" },
    ],
  },
  {
    date: "2025-11-22",
    moves: [
      { player: "Alvin Kamara", to: "JBLA" },
      { player: "Quentin Johnston", to: "Broboken No Jokin" },
    ],
  },
  {
    date: "2025-10-23",
    moves: [
      { player: "Marvin Mims Jr.", to: "A Team Has No Name" },
      { player: "Dylan Sampson", to: "A Team Has No Name" },
      { player: "Woody Marks", to: "A Team Has No Name" },
      { player: "Brian Robinson", to: "Playoff Dark Horse" },
      { player: "Keenan Allen", to: "Playoff Dark Horse" },
      { player: "Christian McCaffrey", to: "Playoff Dark Horse" },
    ],
  },
  {
    date: "2025-10-09",
    moves: [
      { player: "Bijan Robinson", to: "JBLA" },
      { player: "Ollie Gordon II", to: "JBLA" },
      { player: "Jayden Daniels", to: "JBLA" },
      { player: "Josh Downs", to: "Drafted & Managed With AI" },
      { player: "Cam Skattebo", to: "Drafted & Managed With AI" },
    ],
  },
];

// The DTown East Alum Constitution. Built from three sources: Yahoo's live
// 2026 Scoring & Settings page, the full "Fantasy Rules for Vote" record
// (proposals 2017-2025, color-coded green/PASSED or red/REJECTED in the
// source document), and direct confirmation from Mike on anything the
// paper record left ambiguous. Rows flagged "(pending confirmation)" are
// working assumptions, not sourced fact - call those out plainly rather
// than presenting them as settled. See PROPOSAL_HISTORY below for the
// full year-by-year paper trail these articles are distilled from.
const CONSTITUTION_ARTICLES = [
  {
    title: "Format",
    rows: [
      { label: "League type", value: "Head-to-head, live salary-cap (auction) draft" },
      { label: "Teams", value: "12" },
      { label: "Keeper league", value: "Yes" },
      { label: "Draft", value: "Mon, Sep 7, 2026 · live auction" },
      { label: "Keeper deadline", value: "Sun, Sep 6, 2026" },
    ],
  },
  {
    title: "Roster & lineup",
    rows: [
      { label: "Starting lineup", value: "QB, WR, WR, RB, RB, TE, W/R/T, K, DEF" },
      { label: "Bench", value: "7" },
      { label: "IR", value: "2" },
    ],
  },
  {
    title: "Draft & budget",
    rows: [
      { label: "Base cap", value: "$200 flat per owner, every year" },
      { label: "Per-owner floor / ceiling", value: "$170 min · $230 max (ratified 2019, for the 2020 season)" },
      { label: "Trade-adjusted cap", value: "$200 ± net budget dollars traded between drafts, capped at $30/trade (pending confirmation)" },
      { label: "Live draft budget", value: "Trade-adjusted cap minus total keeper cost" },
    ],
    prose: [
      "The 2019 vote that set the $170/$230 bounds also capped single-trade budget transfers at $50. Mike's recollection is that the cap was later reduced — $30 is what's currently documented and consistent with every real trade on file, but the exact vote isn't in the paper record. Treat $30 as the working number until someone can confirm it against old league emails or minutes.",
    ],
  },
  {
    title: "Keepers",
    rows: [
      { label: "Keeper eligibility", value: "Tied to the player, not the draft year — a keeper can be kept indefinitely (ratified 2018)" },
      { label: "Escalating keeper fee (2024+)", value: "Prior salary + (6 + total keepers designated that year), applied to every keeper" },
      { label: "Waiver/FA-acquired player salary", value: "Flat $25 baseline for any player without a salary from a prior draft" },
    ],
    prose: [
      "Before 2024, a kept player's price simply stayed at its original draft salary forever — no escalation. The escalating fee (prior salary + 6, plus 1 more per additional keeper that owner carries that year) was ratified in 2023 for the 2024 season, submitted as \"Option 1\" against a flatter \"Option 2\" that was rejected.",
      "A 2023 proposal to instead base a waiver/FAAB pickup's keeper salary on what was actually spent to acquire them was rejected. The rule already on the books stands: any player kept without a prior draft salary carries a flat $25.",
    ],
  },
  {
    title: "Trades",
    rows: [
      { label: "Review", value: "Commissioner review, 1-day reject window" },
      { label: "Weekly completion", value: "Trades must clear by Wednesday, ahead of Thursday Night Football (moved from Saturday, ratified 2022)" },
      { label: "Season deadline", value: "Nov 28, 2026" },
      { label: "Draft-pick trades", value: "Not allowed" },
      { label: "Protected-player floor", value: "Any player on Yahoo's \"can't cut\" list can't be traded/sold for under $15; commissioner has automatic veto power over trades that undervalue them (ratified 2019)" },
    ],
  },
  {
    title: "Waivers",
    rows: [
      { label: "Format", value: "FAB (blind bid), reverse-standings tiebreak" },
      { label: "Processing", value: "Weekly, Tuesdays" },
      { label: "Max acquisitions/week", value: "4 (no season max)" },
    ],
  },
  {
    title: "Scoring — offense",
    rows: [
      { label: "Passing", value: "20 yds/pt (bonus at 300/400/500 yds) · TD = 6 · INT = -2 (moved from -1 in 2022, to match the defensive reward)" },
      { label: "Rushing / receiving", value: "10 yds/pt (bonus at 100/150/200 yds) · TD = 6" },
      { label: "Receptions", value: "Full PPR — 1 pt/reception" },
      { label: "40+ yard TD bonus", value: "+2 (passing, rushing, receiving)" },
      { label: "Fumbles lost", value: "-2" },
      { label: "2-point conversion", value: "2" },
    ],
  },
  {
    title: "Scoring — kickers & defense",
    rows: [
      { label: "Kicker", value: "PAT = 1 · field goals scored by total yards, 10 yds/pt (decimal scoring ratified 2020)" },
      { label: "Defense/ST", value: "Sack = 1 · INT = 2 · Fumble rec. = 2 · TD = 6 · Safety = 6 · Block kick = 2" },
      { label: "Points allowed", value: "0=10, 1-6=7, 7-13=4, 14-20=1, 21-27=0, 28+=0 (never negative)" },
    ],
  },
  {
    title: "Playoffs",
    rows: [
      { label: "Format", value: "Top 6 teams · weeks 15, 16, 17 (moved from a 4-team field in 2019)" },
      { label: "Tiebreaker", value: "Best regular-season record vs. opponent wins" },
    ],
  },
  {
    title: "Buy-in, payouts & traditions",
    rows: [
      { label: "Buy-in", value: "$200 per owner (doubled from prior years, first effective 2026 season)" },
      { label: "Payouts", value: "Doubled league-wide alongside the buy-in increase" },
      { label: "Last-place penalty", value: "\"The Combine\" — the last-place finisher completes the full NFL combine testing process (ratified 2024)" },
      { label: "Trophy custody", value: "See below — ratified in principle 2024, exact process confirmed directly by Mike, formal language still pending a 2026 vote" },
    ],
    prose: [
      "Trophy chain of custody: the reigning champion holds the trophy through the following season. When that season ends and a new champion is crowned, the outgoing champion delivers the trophy to that season's last-place finisher. Last place has it engraved, then delivers it to the new champion — who holds it through the next season, and the cycle repeats. The 2024 vote established that last place handles the engraving and exchange, but the exact custody chain above was worked out informally over the following offseason rather than voted on directly — it's accurate, but not yet codified.",
    ],
  },
  {
    title: "Governance & amendments",
    rows: [
      { label: "Proposal cycle", value: "Annual, ahead of each season's draft" },
      { label: "Three-strikes rule", value: "A proposal rejected 3 times cannot be brought back for a vote (ratified 2022)" },
      { label: "Ratification threshold", value: "Believed to require a firm majority (at least 7 of 12) — pending Mike's confirmation" },
      { label: "Tied votes", value: "Treated as a rejection, per precedent (2017 tiebreaker proposal)" },
    ],
    prose: [
      "One live wrinkle on the three-strikes rule: the source document itself labels the 2024 rejection of a kicker-removal proposal as the \"SECOND STRIKE,\" which — if the count started with the very same 2022 vote that created the rule — would make 2024 strike two and put the 2024-for-2025 rejection at strike three, meaning this year's kicker-related proposal would already be barred. Mike's recollection is that only two attempts have been made since the rule took effect, making this year's the third and deciding one. Worth settling which reading is correct before the vote goes out.",
    ],
  },
];

// Rules the league is actively deciding or needs to formally resolve this
// cycle - distinct from the ratified articles above. This is the section
// that keeps the document "living" rather than a static snapshot.
const DOCKET_2026 = [
  {
    title: "League Rivals — implement or repeal",
    detail: "Ratified in 2022 for the 2023 season (schedule opens against a designated rival, rematch in week 12 as \"rivalry week,\" rivals set by the commissioner), but never actually built into a schedule. Was a point of contention last season. Needs either real rivalry pairings this year or a formal vote to repeal it.",
  },
  {
    title: "Trophy custody — formal language",
    detail: "The champion-to-last-place-to-new-champion chain (see Buy-in, payouts & traditions above) has been running on informal agreement since 2024. Needs codified language put to a vote this cycle to remove any ambiguity.",
  },
  {
    title: "Remove all computers for the draft — pen and paper only",
    detail: "On the 2025 ballot for the 2026 season. Not yet decided.",
  },
  {
    title: "Remove kicker, or require starting 2 QBs",
    detail: "On the 2025 ballot for the 2026 season. Not yet decided — see the three-strikes note under Governance above; there's a real question of whether this proposal is even eligible for a vote.",
  },
  {
    title: "Most Points For gets the 6th playoff spot",
    detail: "If the Most-Points-For team isn't already in the top 6, they'd claim the last playoff spot. On the 2025 ballot for the 2026 season. Not yet decided.",
  },
  {
    title: "Weekly high-scorer bonus",
    detail: "Top scorer of the week earns bonus money, including in the postseason. On the 2025 ballot for the 2026 season. Not yet decided.",
  },
];

// Full paper trail, 2017-2025, transcribed from the league's own
// color-coded "Fantasy Rules for Vote" record (green = PASSED, red =
// REJECTED, including ties recorded as TIED/REJECTED). seasonVoted is the
// year the vote happened; effectiveSeason is the season labeled in the
// source doc as the year it would take effect. This is the underlying
// evidence the CONSTITUTION_ARTICLES above are distilled from - kept in
// full so nothing gets lost to a future summary.
const PROPOSAL_HISTORY = [
  {
    seasonVoted: 2017,
    effectiveSeason: 2018,
    proposals: [
      { text: "PPR scoring (could be 0.5, 0.25, etc. points per reception)", status: "passed" },
      { text: "Flex roster spot", status: "passed" },
      { text: "Get rid of kickers", status: "rejected" },
      { text: "Auction waivers", status: "passed" },
      { text: "24-hour trade veto window, in lieu of the existing 48 hours (enables Wednesday trades)", status: "passed" },
      { text: "For tied votes, the defending champion's vote is the tiebreaker", status: "tied_rejected" },
      { text: "Playoff teams get first dibs on waivers", status: "rejected" },
      { text: "Fractional yardage points", status: "passed" },
    ],
  },
  {
    seasonVoted: 2018,
    effectiveSeason: 2019,
    proposals: [
      { text: "Three-strike-and-out policy if an owner doesn't set lineups", status: "passed" },
      { text: "Reduce bonus points to 2 pts per bonus level for each position, in lieu of the current model", status: "tied_rejected" },
      { text: "Keeper tied to the player, not the draft year (e.g. draft Carson Wentz in 2018 → keep him through 2021; draft Julio Jones in 2019 → keep him through 2022); keeper lasts forever", status: "passed" },
      { text: "Maximum $50 of next season's auction money can be used in trades during the season and offseason", status: "passed" },
      { text: "A team that is drafted is your team for a full year; offseason trades can take place", status: "passed" },
    ],
  },
  {
    seasonVoted: 2019,
    effectiveSeason: 2020,
    proposals: [
      { text: "Draft clock reduced to 10 seconds", status: "passed" },
      { text: "Weekly loser pays $X to the pot, like the weekly winner takes from the pot", status: "rejected" },
      { text: "No trading cap money after week 5; trading players continues until the week 10 normal deadline", status: "rejected" },
      { text: "Change playoffs from a 4-team to a 6-team field", status: "passed" },
      { text: "Migrate league host site to Ottoneu (FanGraphs) — full salary-cap re-platform with a real-life-style roster and NFL/college universe", status: "rejected" },
      { text: "Handle league matters via email, in lieu of Facebook Messenger", status: "passed" },
      { text: "$1/minute cap deduction next season for every minute an owner is late to the draft room", status: "rejected" },
      { text: "2 keepers allowed, in accordance with current keeper rules", status: "passed" },
      { text: "Any player on Yahoo's \"can't cut\" list can't be traded/sold for less than $15; commissioner gets automatic veto power over player+cash trades that undervalue them", status: "passed" },
      { text: "Minimum draft budget changed to $170, maximum to $230 (from $150 min / $250 max)", status: "passed" },
    ],
  },
  {
    seasonVoted: 2020,
    effectiveSeason: 2021,
    proposals: [
      { text: "Allow pickups/drops of a player until their game kicks off", status: "passed" },
      { text: "Waiver auction price + $10 = keeper value (currently a flat $25 for any FA/waiver addition)", status: "rejected" },
      { text: "Kickers get decimal points (e.g. a 35-yard FG scores 3.5 instead of a flat 3)", status: "passed" },
      { text: "Eliminate week 17 games, add that cash to first-place winnings", status: "rejected" },
      { text: "Remove kicker from the active roster for the 2021 season", status: "rejected" },
      { text: "Punishment for the last-place finisher (contingent follow-up vote on specifics)", status: "rejected" },
    ],
  },
  {
    seasonVoted: 2021,
    effectiveSeason: 2022,
    proposals: [
      { text: "Last-place penalty system — 5 options: \"The Hue Jackman\" (dress in a suit, jump in a body of water), \"The Combine\" (full NFL combine testing), \"Fireman\" (2 hours holding a sign on a street corner), \"Wafflehouse\" (20 hours at a diner, no wifi/computer), \"The Wax\" (chest/back/leg waxing)", status: "rejected" },
      { text: "Move trade deadline from Saturday to Wednesday, ahead of Thursday Night Football", status: "passed" },
      { text: "Remove kickers, add a flex spot to fill the kicker position", status: "rejected" },
      { text: "Three-strikes rule: a rule change rejected 3 times can't be voted on again", status: "passed" },
    ],
  },
  {
    seasonVoted: 2022,
    effectiveSeason: 2023,
    proposals: [
      { text: "Interceptions -2 for QB/offensive player (was -1), to match the +2 defensive reward", status: "passed" },
      { text: "Go back to a snake draft", status: "rejected" },
      { text: "No limit on transactions per week", status: "rejected" },
      { text: "League Rivals — schedule opens against a designated rival in week 1, rematch in week 12 (\"rivalry week\"); rivals set by the commissioner based on prior-season events", status: "passed" },
    ],
  },
  {
    seasonVoted: 2023,
    effectiveSeason: 2024,
    proposals: [
      { text: "Optional one-round snake draft of a college player ($5 of auction budget; costs $15 against auction budget if the player reaches the NFL and is kept; doesn't count against the active roster)", status: "rejected" },
      { text: "Escalating keeper fee — \"Option 1\": salary + $7 (1 keeper), +$16/$8-each (2), +$27/$9-each (3), +$40/$10-each (4), +$55/$11-each (5), +$72/$12-each (6), etc.", status: "passed" },
      { text: "Escalating keeper fee — \"Option 2\" (flatter increments: salary, +$5, +$10, +$15, +$20, +$25)", status: "rejected" },
      { text: "FAAB spend counts as salary for undrafted/waiver-added players, with original draft salary taking precedence if a player is re-added later", status: "rejected" },
      { text: "Remove kicker, replace with a flex spot (SECOND STRIKE)", status: "rejected" },
      { text: "Move draft time/day (4 sub-options, including moving off Labor Day)", status: "rejected" },
    ],
  },
  {
    seasonVoted: 2024,
    effectiveSeason: 2025,
    proposals: [
      { text: "Last-place penalty is \"The Combine\"", status: "passed" },
      { text: "Penalty for nominating a kicker with more than 2 open roster spots (lose $25 in waiver money)", status: "rejected" },
      { text: "Buy-in increased to $200, all payouts doubled", status: "passed" },
      { text: "Last place is responsible for coordinating and completing the trophy engraving and exchange", status: "passed" },
      { text: "Remove kicker", status: "rejected" },
    ],
  },
  {
    seasonVoted: 2025,
    effectiveSeason: 2026,
    proposals: [
      { text: "Remove all computers for the draft — pen and paper only", status: "pending" },
      { text: "Remove kicker, or require starting 2 QBs", status: "pending" },
      { text: "Most Points For in the league gets the 6th playoff spot if not already in the top 6", status: "pending" },
      { text: "Top scorer of the week gets bonus dollars, including postseason", status: "pending" },
    ],
  },
];

const FREE_AGENTS = [
  { name: "Tez Johnson", pos: "WR", team: "TB", snap: 71, usage: "4.2 tgt/gm", airYards: 312, priorSalary: 25 },
  { name: "Kayshon Boutte", pos: "WR", team: "NE", snap: 64, usage: "3.8 tgt/gm", airYards: 287, priorSalary: 25 },
  { name: "Dalton Schultz", pos: "TE", team: "Hou", snap: 68, usage: "5.1 tgt/gm", airYards: 198, priorSalary: 25 },
  { name: "Michael Wilson", pos: "WR", team: "Ari", snap: 55, usage: "3.1 tgt/gm", airYards: 245, priorSalary: 25 },
  { name: "Tyrone Tracy Jr.", pos: "RB", team: "NYG", snap: 47, usage: "9.4 tch/gm", airYards: 0, priorSalary: 9 },
  { name: "Jerry Jeudy", pos: "WR", team: "Cle", snap: 59, usage: "3.4 tgt/gm", airYards: 264, priorSalary: 3 },
  { name: "Rico Dowdle", pos: "RB", team: "Car", snap: 41, usage: "7.8 tch/gm", airYards: 0, priorSalary: 25 },
  { name: "Wil Lutz", pos: "K", team: "Den", snap: 0, usage: "1.6 FG/gm", airYards: 0, priorSalary: 25 },
];

// Real NFL-style weekly time slots, fixed by game-of-the-week rather than
// randomized. Week 1 always opens with the Thursday night kickoff game.
const TIME_SLOTS = [
  "Thu 8:15pm",
  "Sun 1:00pm",
  "Sun 1:00pm",
  "Sun 4:05pm",
  "Sun 8:20pm",
  "Mon 8:15pm",
];

const SEASON_STATUS = {
  year: 2026,
  phase: "preseason",
  draftDate: "2026-09-07",
  keeperDeadline: "2026-09-06",
};
